apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "weaviate-health.fullname" . }}
  annotations:
    {{- if .Values.serviceAccountAnnotations }}
    {{- toYaml .Values.serviceAccountAnnotations | nindent 4 }}
    {{- end }}
